'use strict';
const names={casual:'Everyday casual',professional:'Professional',evening:'Dinner / evening',artistically_expressive:'Artistically expressive',tidy_domestic:'Tidy domestic',cluttered_domestic:'Cluttered domestic',creative:'Creative workspace'};
const $=id=>document.getElementById(id);let target='S02',clothing='casual',background='tidy_domestic',pinned=null;
const label=(c,b,t=target)=>`${t} · ${names[c]} · ${b==='professional'?'Professional workspace':names[b]}`;
const path=(t,c,b)=>DATA.stimuli.find(x=>x.target_id===t&&x.clothing===c&&x.background===b).image_path;
for(const [id,values] of [['clothing',DATA.clothes],['background',DATA.backgrounds]])for(const v of values){const o=document.createElement('option');o.value=v;o.textContent=id==='background'&&v==='professional'?'Professional workspace':names[v];$(id).append(o);}
for(const t of DATA.targets){const b=document.createElement('button');b.id='pick-'+t;b.setAttribute('aria-label','View '+t);const im=document.createElement('img');im.src=path(t,'casual','tidy_domestic');im.alt='Synthetic identity '+t;im.loading='lazy';b.append(im);const s=document.createElement('span');s.textContent=t;b.append(s);b.onclick=()=>{target=t;render(true);};$('cast').append(b);}
function select(c,b){if(!DATA.clothes.includes(c)||!DATA.backgrounds.includes(b))throw Error('Unknown presentation');clothing=c;background=b;render(false);}
function render(rebuild){$('clothing').value=clothing;$('background').value=background;for(const t of DATA.targets)$('pick-'+t).setAttribute('aria-pressed',String(t===target));const file=path(target,clothing,background);$('hero').src=file;$('hero').alt=label(clothing,background);$('download').href=file;$('caption').textContent=label(clothing,background);$('selected-title').textContent=target+' · selected presentation';$('matrix-title').textContent=target+' · complete matrix';$('cue-note').textContent=target==='S03'?'Retained limitation: evening clothing has a moderate or ambiguous occasion cue.':target==='S07'?'Retained limitation: clutter strength is moderate or ambiguous.':'';
 if(pinned){$('comparison').hidden=false;$('pinned').src=pinned.path;$('pinned-caption').textContent=pinned.label;$('compared').src=file;$('compared-caption').textContent=label(clothing,background);}
 if(rebuild){$('matrix').replaceChildren();$('matrix').append(document.createElement('div'));for(const bg of DATA.backgrounds){const e=document.createElement('div');e.className='collabel';e.textContent=bg==='professional'?'Professional workspace':names[bg];$('matrix').append(e);}for(const c of DATA.clothes){const l=document.createElement('div');l.className='rowlabel';l.textContent=names[c];$('matrix').append(l);for(const bg of DATA.backgrounds){const b=document.createElement('button');b.dataset.c=c;b.dataset.b=bg;b.setAttribute('aria-label',label(c,bg));const im=document.createElement('img');im.src=path(target,c,bg);im.alt=label(c,bg);im.loading='lazy';b.append(im);b.onclick=()=>select(c,bg);$('matrix').append(b);}}
 const c=DATA.cards.find(x=>x.target_id===target);$('brief').textContent='CLOTHING\n\n'+DATA.clothes.map(k=>names[k]+': '+c.wardrobe[k]).join('\n\n')+'\n\nDOMESTIC SETTING\n\n'+c.domestic_geometry+'\n\nTIDY / CLUTTERED INVENTORY\n\n'+c.domestic_inventory_and_arrangements+'\n\nPROFESSIONAL WORKSPACE\n\n'+c.backgrounds.professional+'\n\nCREATIVE WORKSPACE\n\n'+c.backgrounds.creative;
 }for(const b of $('matrix').querySelectorAll('button')){b.classList.toggle('active',b.dataset.c===clothing&&b.dataset.b===background);b.setAttribute('aria-pressed',String(b.dataset.c===clothing&&b.dataset.b===background));}}
$('clothing').onchange=e=>select(e.target.value,background);$('background').onchange=e=>select(clothing,e.target.value);$('toggle-room').onclick=()=>select(clothing,background==='cluttered_domestic'?'tidy_domestic':'cluttered_domestic');$('pin').onclick=()=>{pinned={path:path(target,clothing,background),label:label(clothing,background)};render(false);};$('clear').onclick=()=>{pinned=null;$('comparison').hidden=true;};$('hero').onload=()=>{$('load-status').textContent='Lossless image · '+$('hero').naturalWidth+' × '+$('hero').naturalHeight;};$('hero').onerror=()=>{$('load-status').textContent='Image could not load. Please retry or use the downloadable materials.';};render(true);
if(document.modelContext?.registerTool){Promise.resolve(document.modelContext.registerTool({name:'select_synthetic_presentation',description:'Select an illustrative identity and presentation in the visible explorer.',inputSchema:{type:'object',properties:{identity:{type:'string',enum:DATA.targets},clothing:{type:'string',enum:DATA.clothes},background:{type:'string',enum:DATA.backgrounds}},required:['identity','clothing','background'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!DATA.targets.includes(input.identity)||!DATA.clothes.includes(input.clothing)||!DATA.backgrounds.includes(input.background))throw Error('Unknown stimulus');target=input.identity;clothing=input.clothing;background=input.background;render(true);return{identity:target,clothing,background,image:path(target,clothing,background)};}})).catch(()=>{});}
